spring.application.name=Match-History-Manager
playfab.title-id=${PLAYFAB_TITLE_ID}
playfab.secret-key=${PLAYFAB_SECRET_KEY}

#JWT
JwtSecretKey=${JWT_SECRET_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

server.port=8080
